# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shape_pb2 as shape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='layer.proto',
  package='proto',
  syntax='proto2',
  serialized_pb=_b('\n\x0blayer.proto\x12\x05proto\x1a\x0bshape.proto\"Y\n\x05Layer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1b\n\x05shape\x18\x02 \x02(\x0b\x32\x0c.proto.Shape\x12\x13\n\x07weights\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x04\x62ias\x18\x04 \x03(\x02\x42\x02\x10\x01')
  ,
  dependencies=[shape__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='proto.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Layer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='proto.Layer.shape', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weights', full_name='proto.Layer.weights', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='bias', full_name='proto.Layer.bias', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=124,
)

_LAYER.fields_by_name['shape'].message_type = shape__pb2._SHAPE
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER

Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
  DESCRIPTOR = _LAYER,
  __module__ = 'layer_pb2'
  # @@protoc_insertion_point(class_scope:proto.Layer)
  ))
_sym_db.RegisterMessage(Layer)


_LAYER.fields_by_name['weights'].has_options = True
_LAYER.fields_by_name['weights']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_LAYER.fields_by_name['bias'].has_options = True
_LAYER.fields_by_name['bias']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
